name: jzeno_tea
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.2.1+1
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_milk_tea.png
    - assets/images/logoJZ.png
    - assets/images/iconGG.png
    - assets/images/iconFB.png
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik.ttf
        - asset: assets/fonts/rubikB.ttf